version: '3.1'

services:
  discordbot:
    environment:
      MINUTES_TO_WAIT: ${MINUTES_TO_WAIT}
      URL: ${URL}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      USER_ID: ${USER_ID}
      NOT_AVAILABLE_SEND_INTERVAL: ${NOT_AVAILABLE_SEND_INTERVAL}
      DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    build: .

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo/

networks:
  backend: